### ISSUE TITLE
E-Mail that's not multipart produces `NoMethodError`

### ISSUE THREAD

**Issue by freakin-c** [scott/helpy_imap#3]
Hello!
I newly got up and running with a DigitalOcen OCI of Helpy and started configuring the IMAP Email settings. 

The system is preconfigured with:
```
$ ruby -v
ruby 2.4.5p335 (2018-10-18 revision 65137) [x86_64-linux]
$ rails -v
Rails 4.2.11.1
$ rake --version
rake, version 12.3.2
$ rvm --version
rvm 1.29.7 (latest)
```

After Helpy correctly loaded the authors of unread messages in the inbox I knew the connection worked correctly but no tickets appeared. Same with test mails sent from my Thunderbird client - which had been pretty simple test strings without any markup of which Thunderbird creates non-multipart emails. 

Calling `RAILS_ENV=production rake helpy:mailman` in foreground it gave me the following lines including the error:
```
I, [2019-04-08T11:43:41.415479 #1560]  INFO -- : Polling disabled. Checking for messages once.
I, [2019-04-08T11:43:42.283026 #1560]  INFO -- : Got new message from 'email@email.com' with subject 'Support Test'.
#<NoMethodError: undefined method `body' for nil:NilClass>
```

Since the obvious relation to the emails body I added some markup to the test email et voilà: a ticket was created and no error message was printed.

I started looking around for the string `body` in the source files (I read Ruby/Rails for the first time) and found the class `BodyCondition` in `/home/deploy/.rvm/gems/ruby-2.4.5/gems/mailman-0.7.3/lib/mailman/route/conditions.rb` 
providing the method `match(message)`. This method does a check if the passed message is multipart.
If it is and a body part is found that matches some criteria, this part is stored in a variable and returned. If the message is not multipart on the other hand, the `message.body.decoded` is passed to the same method matching but neither is a return value stored nor returned.

That's all for now and I hope my findings and explanations will help you reproduce the bug. Or point out something I missed instead!

Kind regards,
Leon

**Comment by phil8900** [comment]
As I ran into the same issue I tried to dig a bit deeper, and the `conditions.rb` file doesn't seem to be the culprit. For testing purposes and to rule it out, I commented out the line containing `@matcher.match(message.body.decoded)`, but the error still ocurred after that.

Still looking for a solution I looked for occurrences of the keyword "multipart" and stumbled across the following lines of code in the `imap_processor.rb` in the helpy_imap folder:
`  def get_content_from_mail
    if mail_is_mail
      @email.multipart? ? (@email.text_part ? @email.text_part.body.decoded : nil) : @email.body.decoded
    else
      MailExtract.new(@email.body).body
    end
  end`

Curious as I am, I wanted to know if the email.body could be `nil`, although by looking at the code this should never be the case. After testing, I was sure that this is not the case.

As of now, I haven't found a solution, but I'll try to figure it out and I will keep the community updated.

Best regards,
Phil

EDIT: I figured it out! The problem lies in the imap_processor.rb, because a plain-text mail doesn't seem to have a text_part.body, just a .body. The following lines of code will fix this problem:

`  def raw_body_from_mail
  	if @email.multipart?
  		mail_is_mail ? @email.text_part.body.decoded : @email.raw_body
  	else
  		mail_is_mail ? @email.body.decoded : @email.raw_body
    end
  end`
